apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secrets
  labels:
    {{- include "taskflow.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.backend.secrets.DATABASE_URL | quote }}
  BETTER_AUTH_SECRET: {{ .Values.backend.secrets.BETTER_AUTH_SECRET | quote }}
  ANTHROPIC_API_KEY: {{ .Values.backend.secrets.ANTHROPIC_API_KEY | quote }}
  CORS_ORIGINS: {{ .Values.backend.secrets.CORS_ORIGINS | quote }}
