apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.name }}-config
  labels:
    {{- include "taskflow.backend.labels" . | nindent 4 }}
data:
  API_PREFIX: {{ .Values.backend.config.API_PREFIX | quote }}
  API_TITLE: {{ .Values.backend.config.API_TITLE | quote }}
  API_VERSION: {{ .Values.backend.config.API_VERSION | quote }}
  ENVIRONMENT: {{ .Values.backend.config.ENVIRONMENT | quote }}
  DEBUG: {{ .Values.backend.config.DEBUG | quote }}
  JWT_ALGORITHM: {{ .Values.backend.config.JWT_ALGORITHM | quote }}
  JWT_EXPIRY: {{ .Values.backend.config.JWT_EXPIRY | quote }}
  PASSWORD_HASH_ALGORITHM: {{ .Values.backend.config.PASSWORD_HASH_ALGORITHM | quote }}
  PASSWORD_HASH_ROUNDS: {{ .Values.backend.config.PASSWORD_HASH_ROUNDS | quote }}
