apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  labels:
    {{- include "taskflow.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
    {{- if .Values.frontend.service.nodePort }}
    nodePort: {{ .Values.frontend.service.nodePort }}
    {{- end }}
  selector:
    {{- include "taskflow.frontend.selectorLabels" . | nindent 4 }}
