apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.frontend.name }}-secrets
  labels:
    {{- include "taskflow.frontend.labels" . | nindent 4 }}
type: Opaque
stringData:
  BETTER_AUTH_SECRET: {{ .Values.frontend.secrets.BETTER_AUTH_SECRET | quote }}
  BETTER_AUTH_URL: {{ .Values.frontend.secrets.BETTER_AUTH_URL | quote }}
