apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend.name }}-config
  labels:
    {{- include "taskflow.frontend.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_API_URL: {{ .Values.frontend.config.NEXT_PUBLIC_API_URL | quote }}
  NODE_ENV: {{ .Values.frontend.config.NODE_ENV | quote }}
