[build]
command = "cd frontend && npm install --include=dev && npm run build"
publish = "frontend/.next"

[build.environment]
NODE_VERSION = "18"
NEXT_PUBLIC_API_URL = "http://localhost:3000"
NEXT_PUBLIC_BACKEND_URL = "http://localhost:3000"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
