apiVersion: v2
name: taskflow
description: TaskFlow AI Chatbot - Local Kubernetes Deployment for Next.js frontend and FastAPI backend
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - todo
  - chatbot
  - ai
  - nextjs
  - fastapi
maintainers:
  - name: Ahad
home: https://taskflow-ai-chatbot.vercel.app/
sources:
  - https://github.com/ahad1987/Hackathon-II-TODO-Spec-The-Evolution-of-Todo
